#!/usr/bin/env bash
# list-pci-for-passthrough.sh — print the vendor:device IDs and PCI addresses
# of all likely-GPU devices, in the exact format you paste into
# configs/modprobe.d/vfio.conf (ids=...) and into the libvirt <hostdev> block.
#
# Usage:
#     scripts/list-pci-for-passthrough.sh
#     scripts/list-pci-for-passthrough.sh 10de     # only Nvidia (vendor 10de)
#     scripts/list-pci-for-passthrough.sh 10de --write-config
#         # print a ready-to-install /etc/modprobe.d/vfio.conf body
#         # populated with the discovered IDs. Redirect into a file
#         # and diff before installing.

set -euo pipefail

vendor=""
write_config=0
for arg in "$@"; do
    case "$arg" in
        --write-config) write_config=1 ;;
        -h|--help) sed -n '2,15p' "$0"; exit 0 ;;
        *) vendor="$arg" ;;
    esac
done

collect_ids() {
    lspci -Dnn | awk -v v="$vendor" '
        /VGA compatible controller|3D controller|Audio device/ {
            match($0, /\[([0-9a-f]{4}:[0-9a-f]{4})\]/, id)
            if (id[1] == "") next
            if (v != "" && substr(id[1], 1, 4) != v) next
            print id[1]
        }' | paste -sd, -
}

if [[ $write_config -eq 1 ]]; then
    ids="$(collect_ids)"
    if [[ -z "$ids" ]]; then
        echo "No matching devices found — nothing to write." >&2
        exit 1
    fi
    cat <<EOF
# /etc/modprobe.d/vfio.conf — generated by list-pci-for-passthrough.sh
# Discovered on $(hostname) at $(date -Iseconds).

options vfio-pci ids=${ids} disable_vga=1

blacklist nouveau
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
blacklist nvidia_uvm

softdep nouveau pre: vfio-pci
softdep nvidia  pre: vfio-pci
EOF
    exit 0
fi

lspci -Dnn | awk -v v="$vendor" '
    BEGIN {
        printf "%-14s %-40s %-15s\n", "PCI address", "Device", "vendor:device"
        printf "%-14s %-40s %-15s\n", "-----------", "------", "-------------"
    }
    /VGA compatible controller|3D controller|Audio device|USB controller/ {
        match($0, /\[([0-9a-f]{4}:[0-9a-f]{4})\]/, id)
        if (id[1] == "") next
        if (v != "" && substr(id[1], 1, 4) != v) next
        addr=$1
        # trim addr, class label, id
        $1=""; sub(/^[ \t]+/, "", $0)
        sub(/ \[[0-9a-f]{4}:[0-9a-f]{4}\] .*/, "", $0)
        printf "%-14s %-40s %-15s\n", addr, $0, id[1]
    }'

echo
echo "For configs/modprobe.d/vfio.conf (see docs/02-host-setup.md §3):"
ids="$(collect_ids)"
if [[ -n "$ids" ]]; then
    echo "    options vfio-pci ids=${ids} disable_vga=1"
else
    echo "    (no matching devices found)"
fi

# --- Muxless / mobile-Optimus advisory ---------------------------------
# Desktop Nvidia dGPUs expose a VGA (0300) + Audio (0403) pair, sometimes
# with an extra USB controller (0c03). Mobile Optimus laptops typically
# expose only a single 3D controller (0302) — no display outputs, no HDMI
# audio function, no USB-C controller on the card. Warn the user so they
# don't blindly add a second <hostdev> block or a second vfio id.
if [[ "$vendor" == "10de" && -n "$ids" ]]; then
    has_3d=0
    has_vga=0
    has_audio=0
    while read -r line; do
        case "$line" in
            *"3D controller"*)              has_3d=1 ;;
            *"VGA compatible controller"*)  has_vga=1 ;;
            *"Audio device"*)               has_audio=1 ;;
        esac
    done < <(lspci -Dnn | grep -i 'nvidia' || true)

    if (( has_3d && !has_vga && !has_audio )); then
        cat <<'EOF'

Note: this Nvidia device is a class 0302 (3D controller) with no VGA and
no audio function. That is a muxless mobile Optimus card (typical on
gaming and mobile-workstation laptops). Do NOT add a second <hostdev>
block or a second vfio-pci id for an audio function — there isn't one.
Guest audio must go through the emulated ich9/HDA device (already in
configs/libvirt/windows-eng.xml). Looking Glass needs the laptop path:
the kvmfr module, a 64-bit MMIO cap and a Virtual Display Driver in the
guest (docs/04-looking-glass.md §2b; overview in docs/01 "Desktop or
laptop?").
EOF
    elif (( has_vga && !has_audio )); then
        echo
        echo "Note: VGA function found but no HDMI-audio function detected on"
        echo "the Nvidia card. Verify with 'lspci -nn | grep -i nvidia' — some"
        echo "workstation cards omit audio."
    fi
fi
