#!/usr/bin/env bash
# list-evdev-for-passthrough.sh — enumerate the /dev/input/by-id/ symlinks
# suitable for QEMU `input-linux` evdev pass-through, and print the two
# lines you paste into the <qemu:commandline> block of configs/libvirt/
# windows-cad.xml.
#
# Usage:
#     scripts/list-evdev-for-passthrough.sh
#     scripts/list-evdev-for-passthrough.sh --xml    # print ready-to-paste XML
#
# Why /dev/input/by-id/? Bare /dev/input/event* numbers reshuffle across
# boots. by-id/ symlinks are built from USB vendor/product strings and
# stay put unless you swap the device. by-path/ is also stable but
# changes when you re-plug into a different USB port; by-id/ is what
# you want in libvirt.
#
# Only USB HID devices show up in by-id/. A laptop's built-in keyboard
# and trackpad go through i8042/i2c and have no by-id entry — that's
# why evdev pass-through on a laptop needs an external USB keyboard +
# mouse pair (or a wireless combo on a Logitech Unifying receiver, in
# which case both endpoints appear under the receiver's name).

set -euo pipefail

emit_xml=0
for arg in "$@"; do
    case "$arg" in
        --xml)    emit_xml=1 ;;
        -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
        *) echo "Unknown arg: $arg" >&2; exit 2 ;;
    esac
done

if [[ ! -d /dev/input/by-id ]]; then
    echo "/dev/input/by-id/ does not exist — no USB HID devices present." >&2
    exit 3
fi

# Collect KB and mouse candidates. Keyboards end in -event-kbd; pointers
# end in -event-mouse. Anything else (audio HID, hidraw, per-interface
# generic -event-if* nodes) is skipped.
mapfile -t kbds   < <(find /dev/input/by-id -maxdepth 1 -name '*-event-kbd'   2>/dev/null | sort)
mapfile -t mice   < <(find /dev/input/by-id -maxdepth 1 -name '*-event-mouse' 2>/dev/null | sort)

if [[ $emit_xml -eq 1 ]]; then
    if (( ${#kbds[@]} == 0 )); then
        echo "<!-- no USB keyboard with -event-kbd found; plug one in -->" >&2
    fi
    if (( ${#mice[@]} == 0 )); then
        echo "<!-- no USB mouse with -event-mouse found; plug one in -->" >&2
    fi
    (( ${#kbds[@]} == 0 || ${#mice[@]} == 0 )) && exit 3

    kbd="${kbds[0]}"
    mouse="${mice[0]}"
    cat <<EOF
<!-- Generated by scripts/list-evdev-for-passthrough.sh on $(hostname) at $(date -Iseconds).
     Press LEFTCTRL+RIGHTCTRL simultaneously to swap input between host and guest. -->
<qemu:commandline>
  <qemu:arg value='-object'/>
  <qemu:arg value='input-linux,id=kbd1,evdev=${kbd},grab_all=on,repeat=on'/>
  <qemu:arg value='-object'/>
  <qemu:arg value='input-linux,id=mouse1,evdev=${mouse}'/>
</qemu:commandline>
EOF
    exit 0
fi

printf '%-8s %s\n' 'Kind'  'Path (paste this into windows-cad.xml)'
printf '%-8s %s\n' '----'  '--------------------------------------'
if (( ${#kbds[@]} == 0 )); then
    printf '%-8s (none — plug in an external USB keyboard)\n' 'keyboard'
else
    for k in "${kbds[@]}"; do
        printf '%-8s %s\n' 'keyboard' "$k"
    done
fi
if (( ${#mice[@]} == 0 )); then
    printf '%-8s (none — plug in an external USB mouse)\n' 'mouse'
else
    for m in "${mice[@]}"; do
        printf '%-8s %s\n' 'mouse' "$m"
    done
fi

# Advisory when a Logitech Unifying / Lightspeed receiver is present but
# no keyboard endpoint is exposed by it — very common when the user has
# paired only the mouse to the receiver.
receiver=""
for p in "${mice[@]}"; do
    case "$p" in
        *Logitech_USB_Receiver*|*Logitech_Unifying*|*Logitech_MX*|*Logitech_G_Lightspeed*)
            receiver="$p" ;;
    esac
done
if [[ -n "$receiver" && ${#kbds[@]} -eq 0 ]]; then
    cat <<EOF

Note: a Logitech receiver is present ($receiver) but no -event-kbd node
was found. A Unifying / Lightspeed receiver can carry both a keyboard
and a mouse on the same USB device, but they show up as separate evdev
nodes only after each device is paired to the receiver. Pair the
keyboard (Logitech's 'Logi Options+' inside the Windows guest, or
'solaar' on Omarchy) and re-run this script.
EOF
fi

if (( ${#kbds[@]} >= 1 && ${#mice[@]} >= 1 )); then
    cat <<EOF

Ready-to-paste XML block:

    scripts/list-evdev-for-passthrough.sh --xml
EOF
fi
