#!/usr/bin/env bash
# list-pci-for-passthrough.sh — print the vendor:device IDs and PCI addresses
# of all likely-GPU devices, in the exact format you paste into the kernel
# cmdline (vfio-pci.ids=...) and into the libvirt <hostdev> block.
#
# Usage:
#     scripts/list-pci-for-passthrough.sh
#     scripts/list-pci-for-passthrough.sh 10de     # only Nvidia (vendor 10de)
#     scripts/list-pci-for-passthrough.sh 10de --write-config
#         # print a ready-to-install /etc/modprobe.d/vfio.conf body
#         # populated with the discovered IDs. Redirect into a file
#         # and diff before installing.

set -euo pipefail

vendor=""
write_config=0
for arg in "$@"; do
    case "$arg" in
        --write-config) write_config=1 ;;
        -h|--help) sed -n '2,15p' "$0"; exit 0 ;;
        *) vendor="$arg" ;;
    esac
done

collect_ids() {
    lspci -Dnn | awk -v v="$vendor" '
        /VGA compatible controller|3D controller|Audio device/ {
            match($0, /\[([0-9a-f]{4}:[0-9a-f]{4})\]/, id)
            if (id[1] == "") next
            if (v != "" && substr(id[1], 1, 4) != v) next
            print id[1]
        }' | paste -sd, -
}

if [[ $write_config -eq 1 ]]; then
    ids="$(collect_ids)"
    if [[ -z "$ids" ]]; then
        echo "No matching devices found — nothing to write." >&2
        exit 1
    fi
    cat <<EOF
# /etc/modprobe.d/vfio.conf — generated by list-pci-for-passthrough.sh
# Discovered on $(hostname) at $(date -Iseconds).

options vfio-pci ids=${ids} disable_vga=1

blacklist nouveau
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
blacklist nvidia_uvm

softdep nouveau pre: vfio-pci
softdep nvidia  pre: vfio-pci
EOF
    exit 0
fi

lspci -Dnn | awk -v v="$vendor" '
    BEGIN {
        printf "%-14s %-40s %-15s\n", "PCI address", "Device", "vendor:device"
        printf "%-14s %-40s %-15s\n", "-----------", "------", "-------------"
    }
    /VGA compatible controller|3D controller|Audio device|USB controller/ {
        match($0, /\[([0-9a-f]{4}:[0-9a-f]{4})\]/, id)
        if (id[1] == "") next
        if (v != "" && substr(id[1], 1, 4) != v) next
        addr=$1
        # trim addr, class label, id
        $1=""; sub(/^[ \t]+/, "", $0)
        sub(/ \[[0-9a-f]{4}:[0-9a-f]{4}\] .*/, "", $0)
        printf "%-14s %-40s %-15s\n", addr, $0, id[1]
    }'

echo
echo "For the kernel cmdline (see docs/02-host-setup.md):"
ids="$(collect_ids)"
if [[ -n "$ids" ]]; then
    echo "    vfio-pci.ids=${ids}"
else
    echo "    (no matching devices found)"
fi
